# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72cbdb9cf00798a19e7d58e02faacc35cc2ac840a1f7664d677546e2bc21082e6737851590b8ec12b4b4078bbe5ee2f5bc0200fc90675336c9fd2e49c2b9f6fc

test:
  secret_key_base: dd045bf572ba765ce56932d53bef38b168c76440cfeffd653245effb26c8e1e356c1ac8b9ffe88058091d0de07d0d6d56ffab837fe171d36c349007e1eecbc3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
